[tasks.run-server]
install_crate = { crate_name = "cargo-watch", test="cargo watch --help" }
command = "cargo-watch"
args = [
    "-x", "run -- --offline --static ../ui/dist",
]


[tasks.serve]
run_task = [
    { name = ["run-server"] },
]
